samples:
  CHM13:
    fasta: T2T-CHM13v2.fasta
    regions: target_region.bed
    bam: T2T-CHM13v2.bam

# Size of the methylation windows to average over
window_size: 5000

# Size of ALR repeat stretches to include in search of CDR
alr_threshold: 100000

# Distance to merge adjacent CDRs. Can omit.
bp_merge: 1

# Threshold quantile to filter low confidence CDRs. ex 0.1 allows valleys with average value less than the 10% percentile.
quantile_valley_threshold: 0.1

# Threshold percent of the maximum methylation percentage as the minimal prominence of a valley to filter low confidence CDRs.
prominence_perc_valley_threshold: 0.33
