samples:
  CHM13:
    fasta: T2T-CHM13v2.fasta
    regions: target_region.bed
    bam: T2T-CHM13v2.bam

# Size of the methylation windows to average over
window_size: 5000

# Size of ALR repeat stretches to include in search of CDR
alr_threshold: 100000

# Distance to merge adjacent CDRs. Can omit.
bp_merge: 1

# Threshold percent of the average methylation percentage needed as the minimal height of a valley from the median.
# ex. 0.1 allows valleys with a height from the median equal to 10% of the median.
height_perc_valley_threshold: 0.34

prom_perc_valley_threshold: 0.3

bp_alr_merge: 1000

bp_edge: 500000

extend_edges_std: -1
